# Generated by Django 4.1 on 2023-06-07 21:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creationdate', models.DateField(auto_now_add=True)),
                ('frequency_goal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('colour', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='HabitTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit_tracking.day')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit_tracking.habit')),
            ],
        ),
    ]
